inherit_from: .rubocop_todo.yml

Style/ConditionalAssignment:
  Enabled: false

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
    - 'bundle/**/*'
    - 'config/**/*'
    - 'bin/*'